# Generated by Django 2.0 on 2019-12-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_answerlikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
