# Generated by Django 2.0 on 2020-01-19 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0003_auto_20200119_1522'),
        ('area', '0003_auto_20200119_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='area.Area')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='area.City')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='area.Province')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='area.Station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterestCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='interests.Interest')),
            ],
        ),
    ]
