# Generated by Django 2.0 on 2020-01-19 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_interestcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interestcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='interestcategory',
            name='user',
        ),
        migrations.DeleteModel(
            name='InterestCategory',
        ),
    ]
