# Generated by Django 2.0 on 2019-12-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20191229_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
