# Generated by Django 2.0 on 2020-01-17 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
        ('category', '0001_initial'),
        ('questions', '0003_question_total_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAreas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.Area')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.City')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.Province')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCategorys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.AddField(
            model_name='questioncategorys',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='questions.Question'),
        ),
        migrations.AddField(
            model_name='questionareas',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='questions.Question'),
        ),
        migrations.AddField(
            model_name='questionareas',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.Station'),
        ),
    ]
