# Generated by Django 2.0 on 2020-01-17 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20200117_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionareas',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='area.Area'),
        ),
        migrations.AlterField(
            model_name='questionareas',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='area.City'),
        ),
        migrations.AlterField(
            model_name='questionareas',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='area.Province'),
        ),
        migrations.AlterField(
            model_name='questionareas',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='area.Station'),
        ),
        migrations.AlterField(
            model_name='questioncategories',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Category'),
        ),
    ]
