# Generated by Django 2.0 on 2020-01-17 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='area.Area')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='area.City')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='area.Province')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='area.Station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_areas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
