# Generated by Django 2.0 on 2020-01-19 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0002_interestarea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interestarea',
            name='area',
        ),
        migrations.RemoveField(
            model_name='interestarea',
            name='city',
        ),
        migrations.RemoveField(
            model_name='interestarea',
            name='province',
        ),
        migrations.RemoveField(
            model_name='interestarea',
            name='station',
        ),
        migrations.RemoveField(
            model_name='interestarea',
            name='user',
        ),
        migrations.DeleteModel(
            name='InterestArea',
        ),
    ]
